apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-ubuntu
  labels:
    app: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      volumes:
        - name: k8spath
          hostPath:
            path: /k8spath
      containers:
        - name: dev
          volumeMounts:
            - name: k8spath
              mountPath: /data
          image: mchirico/ubuntu:latest
          command: ["/bin/bash", "-c", "echo Hello World; sleep 36d"]



