kind: Pod
apiVersion: v1
metadata:
  name: dev-app
  labels:
    app: simple
spec:
  containers:
    - command:
        - /bin/bash
        - -c
        - |
          echo "Hello World"
          sleep 36d
      image: mchirico/ubuntu:latest
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: accessKey
              optional: false # same as default; "mysecret" must exist
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: secretKey
              optional: false # same as default; "mysecret" must exist
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: sessionToken
              optional: false # same as default; "mysecret" must exist
      name: dev-app
